# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1
executors:
  apache-php:
    docker:
      - image: zfpoly/apache-php:7.4.0
    working_directory: ~/app-tmp

jobs:
  build:
    executor: apache-php
    steps:
      - checkout
      - run: mv .ciscripts/01_build.sh ./01_build.sh && chmod +x 01_build.sh
      - run: ./01_build.sh
      - run: rm ./01_build.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_unitaire:
    executor: apache-php
    steps:
      - attach_workspace:
          at: ~/app-tmp
      - run: mv .ciscripts/02_test_unitaire.sh ./02_test_unitaire.sh && chmod +x ./02_test_unitaire.sh
      - run: ./02_test_unitaire.sh
      - run: rm ./02_test_unitaire.sh

  test_fonctionnel:
    executor: apache-php
    steps:
      - attach_workspace:
          at: ~/app-tmp
      - run: mv .ciscripts/02_test_fonctionnel.sh ./02_test_fonctionnel.sh && chmod +x ./02_test_fonctionnel.sh
      - run: ./02_test_fonctionnel.sh
      - run: rm ./02_test_fonctionnel.sh

  deliver_to_main:
    executor: apache-php
    steps:
      - attach_workspace:
          at: ~/app-tmp
      - run: mv .ciscripts/03_deliver_to_main.sh ./03_deliver_to_main.sh && chmod +x ./03_deliver_to_main.sh
      - run: ./03_deliver_to_main.sh
      - run: rm ./03_deliver_to_main.sh

  deliver_to_hub:
    docker: 
      - image: docker:20.10-git
    working_directory: ~/app-tmp
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/app-tmp
      - run: mv .ciscripts/04_deliver_to_hub.sh ./04_deliver_to_hub.sh && chmod +x ./04_deliver_to_hub.sh
      - run: ./04_deliver_to_hub.sh

workflows:
  version: 2
  build-test-deliver:
    jobs:
      - build:
          filters:
             branches:
              only:
                 - develops
                 - mains
      - test_unitaire:
          requires:
            - build
          filters:
             branches:
              only:
                 - develops
                 - mains
      - test_fonctionnel:
          requires:
            - build
          filters:
             branches:
              only:
                 - develops
                 - mains
      - deliver_to_main:
          requires:
            - test_unitaire
            - test_fonctionnel
          filters:
             branches:
              only:
                 - develops
      - deliver_to_hub:
          requires:
            - test_unitaire
            - test_fonctionnel
          filters:
             branches:
              only:
                 - mains
